### ISSUE TITLE
records-from-csv not working properly

### ISSUE THREAD

**Issue by felipeacsi** [Amelia-Mowers/typst-tabut#11]
Hello, thank you for this great package. It's really promising.

I wanted to try `records-from-csv` but I'm having trouble working with it both in the app and local.

---

Locally I have this `test.typ`:

```typst
#import "@preview/tabut:1.0.0": records-from-csv

#records-from-csv("csv/materials.csv")
```

Here is the output from my system trying to compile a test file:

```
Compilation started at Wed Jan 31 15:20:41

typst compile test.typ test.pdf
error: file not found (searched at /home/user/.cache/typst/packages/preview/tabut/1.0.0/materials.csv)
    ┌─ @preview/tabut:1.0.0/lib.typ:167:23
    │
167 │     let data-raw = csv(filename);
    │                        ^^^^^^^^

help: error occurred in this call of function `records-from-csv`
  ┌─ test.typ:3:1
  │
3 │ #records-from-csv("materials.csv")
  │  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compilation exited abnormally with code 1 at Wed Jan 31 15:20:41
```

`records-from-csv` is trying to find the csv file in the path of the package so it won't work. I have read that typst still does not have a way to work with paths so I don't know if it could be possible to fix this function yet.

I think I can just copy-paste `records-from-csv` and use it in another file for now, but it could be great if this is possible from the package itself.

**Comment by Amelia-Mowers** [comment]
Thank you for your feedback.

It appears to be that by typst design plugin functions can't access files outside of the plugin itself.

But I can fix by having it so that `records-from-csv` takes an input of an already parsed csv file so: 
`records-from-csv(csv("file-path"))`
instead of:
`records-from-csv("file-path")`

Apologies for the inconvenience.

**Comment by Amelia-Mowers** [comment]
Fixed, I'll send in a pull request in the package repo, and hopefully the new version will be available later today or tomorrow.

**Comment by Amelia-Mowers** [comment]
Merged into main package repo.

**Comment by felipeacsi** [comment]
> But I can fix by having it so that `records-from-csv` takes an input of an already parsed csv file so: 
> `records-from-csv(csv("file-path"))`

Yes, I think is the best alternative right now.

Thank you for the quick fix!
