### ISSUE TITLE
tabut 1.0.2 not available on Typst packages

### ISSUE THREAD

**Issue by felipeacsi** [Amelia-Mowers/typst-tabut#15]
Hello,

I've been using tabut 1.0.1 but I need the fix done for CSV files done in 1.0.2 and I noticed that 1.0.2 is not available from Typst packages. Is this a known issue? How can I help?

**Comment by Amelia-Mowers** [comment]
Hello, apologies and thank you for reaching out. Some life stuff came up which caused my lack of updates. I'll work on pushing the updated version to the package repo today, and that should be available by tonight or tomorrow.

________________________________
From: felipeacsi ***@***.***>
Sent: Monday, April 15, 2024 11:34:15 AM
To: Amelia-Mowers/typst-tabut ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Amelia-Mowers/typst-tabut] tabut 1.0.2 not available on Typst packages (Issue #15)


Hello,

I've been using tabut 1.0.1 but I need the fix done for CSV files done in 1.0.2 and I noticed that 1.0.2 is not available from Typst packages. Is this a known issue? How can I help?

**Comment by felipeacsi** [comment]
Ok, much appreciated.

Thank you for your quick answer!

**Comment by Amelia-Mowers** [comment]
Placed a pull request to the package repo:

https://github.com/typst/packages/pull/553

**Comment by felipeacsi** [comment]
It was merged and now it works. Thank you so much!
